### ISSUE TITLE
Add cmd-line option to open file

### ISSUE THREAD

**Issue by pgdurand** [pgdurand/BlastViewer#3]
Add a cmd-line option at least to open file when starting BV from the cmd-line

**Comment by bfristensky** [comment]
What is the syntax for opening blastviewer with a file from the Linux command line? I have tried numerous things, including fully qualified paths, but blastviewer always pops up empty.
eg. 
java -jar blastviewer-5.3.0.jar mousecat.blastn.xml

I know the file is good, because I can read it manually into blastviewer using the Open button.

I am particularly interested in getting this to work because blastviewer would be a nice addition to my BIRCH bioinformatics system. BIRCH runs BLAST searches from a GUI, and pops up output in a web browser and a spreadsheet-style program. A tutorial illustrating how this works can be found at 
[http://home.cc.umanitoba.ca/~psgendb/birchhomedir/BIRCHDEV/public_html/tutorials/bioLegato/blastdb/blastdb.html]
 Getting output to come up in blastviewer would expand the user's ability to work with the output.

**Comment by pgdurand** [comment]
well I didn't add this feature until now... however, 2 years ago I started the dev of the Java Web Start release of BlastViewer that is capable of doing what you'd like to do (look at the 'jws' branch of BlastViewer project on Github)... but, Oracle stopped the use of JWS, so I do not know what direction to follow...

**Comment by bfristensky** [comment]
My own interest would be in blastviewer as a standalone desktop application, rather than using JWS. 
The idea behind BIRCH is to have a seamless flow of data from one step to the next. BIRCH has its own spreadsheet-style program for displaying and retrieving BLAST hits, but blastviewer is such a full-featured and intuitive program that I'd like to be able to have output also pop up in blastviewer.

My guess is that adding a command line option for the input file would be easy. Let me know if you are willing to add this feature.
Thanks!

**Comment by pgdurand** [comment]
ok, I understand your query... I think I should have some time during July to add that command-line option to the software... stay tuned !

**Comment by bfristensky** [comment]
Great. If it's any incentive, I tried a lot of blast output viewers, and was most impressed with blastviewer. I'm looking forward to seeing the revised version.

**Comment by pgdurand** [comment]
Hi.

Work done, please read: 
https://github.com/pgdurand/BlastViewer/wiki#use-command-line-arguments

Checkout latest release of BlastViewer implementing command-line arguments: 
https://github.com/pgdurand/BlastViewer/releases/tag/v5.4.0

Let me know whether implemented features fit your needs.

**Comment by bfristensky** [comment]
Many thanks. I'll give it a try tomorrow.


====================================================
Brian Fristensky
Department of Plant Science
University of Manitoba
Winnipeg, MB R3T 2N2  CANADA
Phone: 204-474-6085
FAX: 204-474-7528
frist@cc.umanitoba.ca<mailto:frist@cc.umanitoba.ca>
http://home.cc.umanitoba.ca/~frist/<http://home.cc.umanitoba.ca/~frist>
===========================================================
I can't say that running is my favorite thing to do in space:
after you get used to floating everywhere, it feels odd and a
little unfair to have to move your legs to go nowhere....
Astronauts who are serious runners seem to mind less; in 2007,
Suni Wiliams ran the Boston Marathon in space, which took her
only 4 hours and 24 minutes.
    -- Chirs Hadfield, AN ASTRONAUT'S GUIDE TO LIFE ON EARTH.
===========================================================



________________________________
