### ISSUE TITLE
reorder columns

### ISSUE THREAD

**Issue by Aciole-David** [pgdurand/BlastViewer#8]
Hello, @pgdurand 

I would like to thank you for the great work with BlastViewer and ask if a way to reorder columns could be implemented.
Thank you.

Cheers.
David

**Comment by pgdurand** [comment]
Hi David,
actually the structure of the Hit Table of BlastViewer uses a hierarchical strtucture (i.e. some kind of tree with two levels) to gather query information vs hit information. It means that the header of the table contains two rows, but only one is displayed, by design. Unfortunately, that structure prevents the easy reordering of columns. So for now, I would not be able to do code update... but I keep it in the "todo" list of the software for future updates.
Cheers,
Patrick
